#!/bin/bash

set -exo pipefail

if [[ ! -f /tmp/project.txt ]]; then
  echo "Rafay Project file not created. Safe to proceed with CI/CD run."
  exit 0
else
  echo "Rafay Project file found. Proceeding with checks.."
fi

export PROJECT=$(cat /tmp/project.txt)
CLUSTER1=$(echo "$PROJECT" | sed 's/$/-cluster1/')

# Check: CLI configuration file present
#
if [[ ! -f workspace/config.json ]]; then
  fail-message "You are missing the 'workspace/config.json' file. Review the Setup the Rafay CLI (rctl) section."
  exit 1
fi

# Check: CLI configuration
#
if [[ ! -d ~/.rafay ]]; then
  fail-message "rctl is not configured. Run: 'rctl config init workspace/config.json'"
  exit 1
fi

# Check: API connectivity / Credentials
#
PROJECTS=$(rctl get projects)
if [[ $? -ne 0 ]]; then
    fail-message "Unable to communicate with the Rafay Controller, please verify your credentials are correct. Review the Setup the Rafay CLI (rctl) section."
  exit 1
fi

# Check: Project created
#
if [[ `echo $PROJECTS | grep $PROJECT | wc -l` -ne 1 ]]; then
  fail-message "Could not find the $PROJECT project. Please review the Log in the Rafay Console section."
  exit 1
fi

# Check: Clusters are imported
#
CLUSTER1_STATUS=$(rctl get clusters --project $PROJECT -o json | jq --arg cluster1 "$CLUSTER1" -r '.[] | select(.name | contains($cluster1)).status')
if [ "$CLUSTER1_STATUS" != "READY" ]; then
  fail-message "The cluster $CLUSTER1 is not ready. The Operational Status must report "READY". Review the Import a Kubernetes Cluster using the CLI section in Part 1."
exit 1
fi

CLUSTER1_HEALTH=$(rctl get clusters --project $PROJECT -o json | jq --arg cluster1 "$CLUSTER1" -r '.[] | select(.name | contains($cluster1)).health')
if [ "$CLUSTER1_HEALTH" != 1 ]; then
  fail-message "The $CLUSTER1 cluster is not ready. The Control plane must show up as "HEALTHY". Review the Import a Kubernetes Cluster using the CLI section in Part 1."
  exit 1
fi