#!/bin/bash

set -x

cat <<EOF > /tmp/config.json
{
    "profile": "",
    "api_key": "bec27c4b311ad9084e0894653fadc93f347a13fd",
    "api_secret": "$WWT_SECRET",
    "project_id": "mpl1qx2",
    "rest_endpoint": "console.rafay.dev",
    "ops_endpoint": "ops.rafay.dev"
}
EOF

if [[ -f /tmp/project.txt ]]; then

  rctl config init /tmp/config.json
  export project=$(cat /tmp/project.txt)
  cluster1=$(echo "$project" | sed 's/$/-cluster1/')
  ns=$(echo "$project" | sed 's/$/-ns/')

  # Common to all Tracks
  rctl --project $project delete cluster $cluster1 --force --yes

  # Unique to Track 4
  rctl --project $project delete blueprint node-exporter-bp
  rctl --project $project delete addon node-exporter-add-on
  rctl --project $project delete ns $ns

  # Common to all Tracks
  rctl delete project $project

fi