#!/bin/bash
set -euxo pipefail

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api 
do
    sleep 1 
done

# Enable bash completion for kubectl
echo "Enabling bash completion for kubectl"
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc

## Install Rafay CLI
echo "Installing rctl....."
apt-get install -y bzip2
wget https://s3-us-west-2.amazonaws.com/rafay-prod-cli/publish/rctl-linux-amd64.tar.bz2
tar vfx rctl-linux-amd64.tar.bz2
mv rctl /usr/local/bin/rctl
chmod +x /usr/local/bin/rctl
rm -rf rctl-linux-amd64.tar.bz2 build.info
